import { NodeStatsType } from "./Stats";

export type Node = {
  id: string;
  type: string;
  base?: boolean;
  tier?: "small" | "medium" | "large";
  angle?: number;
  distance?: number;
};

export type NodeTypeMetadata = {
  name: string;
  description: string[];
  hasIcon?: boolean;
  iconOffset?: number;
  hasAsset?: boolean;
  unselectedAsset?: string;
  selectableAsset?: string;
  selectedAsset?: string;
  color: string;
  cost: number;
  stats?: NodeStatsType;
};

export type SkillNodesType = {
  types: { [key: string]: NodeTypeMetadata };
  nodes: { [key: string]: Node };
  edges: { [key: string]: string[] };
};

// ANGLE LINES
export const LinesAngles = [
  15, 45, 75, 105, 135, 165, 195, 225, 255, 285, 315, 345,
];

const SHROUD_TIME_TEXT =
  "<b>Miasma-Zeit</b><br/>Läuft diese Zeit aus, wird das Miasma dich verschlingen.";
const BLOCK_BREAKER =
  "<b>Block Brecher</b><br/>Dieser Spezialangriff erh&ouml;ht die Bet&auml;ubungsleiste eines Gegners um das Doppelte, wenn er getroffen wird.";
const OVERPOWER =
  "<b>&Uuml;berw&auml;ltigen</b><br/>Um einen Gegner zu &uuml;berw&auml;ltigen, f&uuml;llst die seine Bet&auml;ubungsleiste, indem du angreifst, w&auml;hrend er blockt oder seine Angriffe parierst.";
const WET =
  "<b>Wet</b><br/>Reduces Stamina and Stamina Regeneration by <b>30%</b> for <b>15</b> minutes. Warmth reduces the remaining duration.";
const SOAKED =
  "<b>Soaked</b><br/>Reduces Stamina and Stamina Regeneration by <b>30%</b> for <b>30</b> seconds. Also reduces <b>Ice and Shock Resistances</b> by <b>30%</b> but increases <b>Fire Resistances</b> by <b>30%</b>.<br><b>Soaked</b> can be applied to enemies. <br><b>Soaked</b> duration can not be reduced by warmth and <b>Wet</b> debuff starts after it is over.";

const SkillNodes: SkillNodesType = {
  types: {
    GIANT_SLAYER_HOOK: {
      name: "RIESENTÖTER-HAKEN",
      description: [
        "Benutze deinen Greifhaken, um dich im Kampf zu gro&szlig;en Feinden zu ziehen.",
      ],
      hasIcon: true,
      color: "gold",
      cost: 5,
    },
    GROUNDING_HOOK: {
      name: "BRUCHLANDUNGS-HAKEN",
      description: [
        "Benutze deinen Greifhaken, um fliegende Gegner im Kampf zu dir zu ziehen.",
      ],
      hasIcon: true,
      color: "gold",
      cost: 2,
    },
    SAVIOUR: {
      name: "ERLÖSER",
      description: [
        "Du ben&ouml;tigst nur 3 statt 6 Sekunden, um einen <b>Verb&uuml;ndeten wiederzubeleben.</b>",
      ],
      color: "gold",
      cost: 2,
    },
    BACKSTAB_DAMAGE: {
      name: "HINTERHALT-SCHADEN",
      description: ["Erh&ouml;ht den Schaden, den du von hinten verursachst, um 25%."],
      color: "gold",
      cost: 2,
    },
    OPPORTUNITY: {
      name: "GELEGENHEIT",
      description: [
        "Erh&ouml;ht den Multiplikator des Gnadenlosen Angriffs und des Schleichangriffs um 100%.",
      ],
      color: "gold",
      cost: 3,
    },
    MINER: {
      name: "BERGARBEITER",
      description: [
        "Beim Abbau von Ressourcen besteht eine Chance von 10%, zus&auml;tzlich Ressourcen zu gewinnen.",
      ],
      color: "gold",
      cost: 4,
    },
    LUMBERJACK: {
      name: "HOLZFÄLLER",
      description: [
        "Holzf&auml;ller-&Auml;xte verursachen 30% mehr Schaden gegen Holzobjekte, einschlie&szlig;lich B&auml;ume.",
      ],
      color: "gold",
      cost: 2,
    },
    QUALITY_GEAR: {
      name: "HOCHWERTIGE AUSRÜSTUNG",
      description: ["Alle Werkzeuge verlieren 50% langsamer an Haltbarkeit."],
      color: "gold",
      cost: 2,
    },
    MASON: {
      name: "STEINMETZ",
      description: [
        "Die Spitzhacke verursacht 30% mehr Schaden gegen Steinobjekt, einschlie&szlig; Ressourcenadern.",
      ],
      color: "gold",
      cost: 2,
    },
    FISHERMANS_RESOLVE: {
      name: "FISHERMAN'S RESOLVE",
      description: [
        "Increases your Fishing Endurance by <b>30%</b>.",
        "Allows for extended battles with hooked fish.",
      ],
      color: "gold",
      cost: 5,
    },
    POWER_PARRY: {
      name: "PRACHTPARADE",
      description: [
        "L&auml;sst den Gegner bei Parierangriffen schneller bet&auml;ubt werden.",
        "<b>Parieren</b><br>Wenn du mit einem Schild ausger&uuml;stet bist, dr&uuml;cke <b>[Rechte Maustaste],</b> um zu blocken. Ein gut getimter Block <b>pariert</b> den Angriff.",
      ],
      color: "gold",
      cost: 2,
    },
    ATTR_SPIRIT: {
      name: "WILLENSKRAFT",
      description: [
        "Erh&ouml;ht dein Willenskraftattribut um 1.",
        "Erh&ouml;ht das Mana um 20 pro Attributspunkt.",
      ],
      color: "blue",
      cost: 1,
      stats: { SPIRIT: 1 },
    },
    ATTR_INT: {
      name: "INTELLIGENZ",
      description: [
        "Erh&ouml;ht dein Intelligenzattribut um 1.",
        "Erh&ouml;ht den Magieschaden um 5% pro Attributspunkt.",
      ],
      color: "blue",
      cost: 1,
      stats: { INT: 1 },
    },
    ATTR_CONS: {
      name: "KONSTITUTION",
      description: [
        "Erh&ouml;ht dein Konstitutionsattribut um 1.",
        "Erh&ouml;ht deine Gesundheit um 50 pro Attributspunkt.",
      ],
      color: "red",
      cost: 1,
      stats: { CONS: 1 },
    },
    ATTR_STR: {
      name: "STÄRKE",
      description: [
        "Erh&ouml;ht dein St&auml;rkeattribut um 1.",
        "Erh&ouml;ht den Nahkampfschaden um 5% pro Attributspunkt.",
      ],
      color: "red",
      cost: 1,
      stats: { STR: 1 },
    },
    ATTR_ENDURANCE: {
      name: "KONDITION",
      description: [
        "Erh&ouml;ht dein Konditionsattribut um 1.",
        "Erh&ouml;ht die Ausdauer um 10 pro Attributspunkt.",
      ],
      color: "green",
      cost: 1,
      stats: { ENDURANCE: 1 },
    },
    ATTR_DEX: {
      name: "GESCHICK",
      description: [
        "Erh&ouml;ht dein Geschickattribut um 1.",
        "Erh&ouml;ht den Schaden von B&ouml;gen und Dolchen um 5% pro Attributspunkt.",
      ],
      color: "green",
      cost: 1,
      stats: { DEX: 1 },
    },
    WELL_RESTED: {
      name: "GUT AUSGERUHT",
      description: [
        "Die Grunddauer f&uuml;r den Ausgeruht Buff wird um 5 Minuten erh&ouml;ht.",
        "Erh&ouml;he den Komfort in deiner Basis, um die Dauer weiter zu verl&auml;ngern.",
      ],
      color: "gold",
      cost: 1,
    },
    SNEAK_ATTACK: {
      name: "SCHLEICHANGRIFF",
      description: [
        "Der <b>Schleichangriff</b> f&uuml;gt ahnungslosen Gegnern massiven 10-fachen Schaden zu.",
        "Um ihn auszul&ouml;sen, schleiche dich an einen Gegner heran und dr&uuml;cke <b>[E]</b>.",
      ],
      hasIcon: true,
      color: "gold",
      cost: 3,
    },
    MERCILESS_ATTACK: {
      name: "GNADENLOSER ANGRIFF",
      description: [
        "F&uuml;hre einen gnadenlosen Angriff aus, indem du [E] dr&uuml;ckst, um einen Gegner, den du &uuml;berw&auml;ltigt hast, massiven Schaden zuzuf&uuml;gen.",
        OVERPOWER,
      ],
      hasIcon: true,
      color: "gold",
      cost: 2,
    },
    UPDRAFT: {
      name: "AUFWIND",
      description: [
        "Wenn du beim Gleiten die Sprungstaste drückst, bekommst du einen kleinen Höhenschub. Diese Fähigkeit kann einmal pro Flug eingesetzt werden. Kosten: 120 Mana.",
      ],
      hasIcon: true,
      color: "green",
      cost: 4,
    },
    BEGONE: {
      name: "HINFORT",
      description: [
        "Ein magischer Schlag, der getroffene Feinde wegstößt und betäubt.",
        "Ersetzt deine unbewaffneten Angriffe, solange du das nötige Mana zur Verfügung hast: <b>30 Mana</b>",
      ],
      hasIcon: true,
      color: "blue",
      cost: 3,
    },
    RADIANT_AURA: {
      name: "STRAHLENDE AURA",
      description: [
        "Alle Brutfeinde im Umkreis von 10 Meterm erhalten pro Intelligenzpunkt 1 Feuerschaden pro Sekunde.",
      ],
      hasIcon: true,
      color: "blue",
      cost: 3,
    },
    WATER_AURA: {
      name: "WASSERAURA",
      description: [
        "Du verströmst eine heilende Aura. Sie heilt alle verletzten Verbündeten im Umkreis von 15 Meter. Die Heilung skaliert mit deinem Intelligenz-Attribut (1 Lebenspunkt für je 2 Punkte Intelligenz).",
      ],
      hasIcon: true,
      color: "blue",
      cost: 3,
    },
    MARTYR: {
      name: "MÄRTYRER",
      description: [
        "Wenn du von einem Feind getötet wirst, werden alle Verbündeten im Umkreis von 50 Metern um 50% ihrer Maximalen Gesundheit geheilt.",
        "Außerdem erhalten sie einen <b>Letzten Segen</b>, der ihre maximalen Lebenspunkte für 15 Minuten um 100 erhöht.",
      ],
      hasIcon: true,
      color: "blue",
      cost: 5,
    },
    DIVINE_SURGE: {
      name: "DIVINE SURGE",
      description: [
        "Healing spells can perform Critical Strikes that scale with your Critical Strike Damage.",
      ],
      color: "blue",
      cost: 5,
    },
    RIGHTEOUS_FIRE: {
      name: "RIGHTEOUS FIRE",
      description: [
        "Healing any target with a spell triggers a burst of fire that deals <b>50%</b> of the heal amount as <b>Fire</b> damage to nearby <b>Fell</b> enemies.",
      ],
      color: "blue",
      cost: 5,
    },
    BLINK: {
      name: "TELEPORT",
      description: [
        "Ersetzt die Ausweichrolle duch einen Kurzstrecken-Teleport.",
      ],
      hasIcon: true,
      color: "blue",
      cost: 4,
    },
    EVASION_ATTACK: {
      name: "AUSWEICHANGRIFF",
      description: [
        "Wenn du mit einer Nahkampfwaffe ausgerüstet bist, kannst du mit <b>[Linke Maustaste]</b> einen Ausweichangriff ausführen, welcher dich auf den Gegner zustürmen lässt und mehr Waffenschaden verursacht.",
        BLOCK_BREAKER,
      ],
      hasIcon: true,
      color: "red",
      cost: 4,
    },
    EARTH_AURA: {
      name: "ERDAURA",
      description: [
        "Schützt Verbündete und dich selbst und reduziert den eingehenden Schaden um 10%.",
      ],
      hasIcon: true,
      color: "red",
      cost: 5,
    },
    NEMESIS: {
      name: "NEMESIS",
      description: [
        "Wenn ein Verbündeter die Aufmerksamkeit eines Feindes auf sich zieht, gilt das auch für dich.",
      ],
      hasIcon: true,
      color: "red",
      cost: 5,
    },
    SHOCKWAVE: {
      name: "SCHOCKWELLE",
      description: [
        "Löse eine Schockwelle aus, wenn du einen Angriff parierst oder einen Gegner überwältigst.",
        "Die Schockwelle stößt Feinde in der Nähe zurück und erhöht ihre Betäubungsleiste. Der Betäubungswert skaliert mit deinem Stärkeattribut.",
        OVERPOWER,
      ],
      hasIcon: true,
      color: "red",
      cost: 3,
    },
    HEAVY_SPECIALIZATION: {
      name: "SCHWERE SPEZIALISIERUNG",
      description: ["Ermöglicht es dir, schneller mit zweihändigen Waffen anzugreifen."],
      hasIcon: true,
      color: "red",
      cost: 5,
    },
    BASH: {
      name: "BASH",
      description: [
        "Deiner Parade fügt dem Gegner 20 Wucht Schaden zu. Der Schaden wird durch dein Stärkeattribut erhöht.",
      ],
      hasIcon: true,
      color: "red",
      cost: 5,
    },
    WHIRLWIND_CRESCENDO: {
      name: "WHIRLWIND CRESCENDO",
      description: [
        "When equipped with a Two-Handed weapon, trigger a whirl attack at the end of an attack chain.",
        "<b>Cost</b>: 75 Stamina",
      ],
      hasIcon: true,
      color: "red",
      cost: 5,
    },
    CRASH_DOWN_ATTACK: {
      name: "SPRUNGANGRIFF",
      description: [
        "Wenn du mit einer Nahkampfwaffe ausgerüstet bist, kannst du einen Sprungangriff ausführen, der 50% mehr Waffenschaden in einem kleinen Explosionsradius verursacht.",
        "Der Sprungangriff kostet Ausdauer entsprechend dem Gewicht der Waffe. Funktioniert nicht mit Werkzeugen.",
        "<b>Kosten</b>: 35-60 Ausdauer",
        BLOCK_BREAKER,
      ],
      hasAsset: true,
      selectedAsset: "crash_down_attack_active.png",
      unselectedAsset: "crash_down_attack.png",
      color: "red",
      cost: 3,
    },
    DOUBLE_JUMP: {
      name: "DOPPELSPRUNG",
      description: ["Erlaubt es, in der Luft ein zweites Mal zu springen."],
      hasIcon: true,
      iconOffset: 10,
      color: "green",
      cost: 4,
    },
    DESSERT_STOMACH: {
      name: "DESSERTMAGEN",
      description: ["Du erhältst einen zusätzlichen Nahrungs-Slot."],
      hasIcon: true,
      color: "green",
      cost: 4,
    },
    LAST_MEAL: {
      name: "LAST MEAL",
      description: [
        "Your Food buffs persist through death, but they last half as long.",
      ],
      color: "green",
      cost: 5,
    },
    EAGLE_EYE: {
      name: "ADLERAUGE",
      description: [
        "Erhöht den Zoom beim Zielen mit dem Bogen erheblich.",
        "Halte zum Zielen [Rechte Maustaste], während der Bogen in der Aktionsleiste ausgewählt ist.<br />Alternativ kannst du [Q] halten, um mit deinem angelegten Bogen zu zielen.)",
      ],
      hasIcon: true,
      color: "green",
      cost: 3,
    },
    MULTI_SHOT: {
      name: "MULTISCHUSS",
      description: [
        "Wenn du normale Pfeile verwendest, besteht eine 20%ige Chance, dass du eine Salve von Pfeilen abschießt, die sich leicht ausbreitet.",
        "Das kostet zusätzlich Pfeile, wird aber bei Spezialpfeilen nicht ausgelöst.",
      ],
      hasIcon: true,
      color: "green",
      cost: 3,
    },
    MULTI_SHOT_SPREAD: {
      name: "MULTISCHUSSTEILUNG",
      description: [
        `Fügt deinem "Pfeilhagel" aus der Fertigkeit "Multischuss" eine Chance von 25% hinzu, ein zusätzliches Projektil zu erzeugen.`,
        "Dieses zusätzliche Geschoss wird nicht von deiner Munition abgezogen.",
      ],
      color: "green",
      cost: 4,
    },
    MULTI_SHOT_TRIGGER: {
      name: "MULTISCHUSS TRIGGER",
      description: [
        `ALLE Pfeile, einschließlich der Spezialpfeile, können "Multischuss" auslösen.`,
        "Die speziellen Mulitschuss-Geschosse werden von deiner Munition abgezogen.",
      ],
      color: "green",
      cost: 3,
    },
    BEE_STING: {
      name: "BIENENSTICH",
      description: [
        "Wenn du deinen Bogen in der Luft ziehst, wird dein Fll für eine kurze Zeit verlangsamt. Jeder Schuss gibt dir einen kleinen Schub, um mehr Zeit in der Luft zu bekommen.",
        "Kosten: 10 Ausdauer pro Sekunde",
      ],
      hasIcon: true,
      color: "green",
      cost: 3,
    },
    SHELL_SHOCK: {
      name: "GRANATENSCHOCK",
      description: [
        "Infundiere deine <i>Fernkampfsprengstoffe</i> mit Mana. Sie betäuben Gegner jetzt bis zu 1 Sekunde lang.",
        "Manakost: 5 pro betäubten Gegner",
      ],
      hasIcon: true,
      color: "green",
      cost: 3,
    },
    COUNTERSTRIKE: {
      name: "GEGENSCHLAG",
      description: [
        "Nachdem du Schaden erhalten hast, besteht eine 20%ige Chance, <b>50% des Schadens als Feuerschaden</b> auf den Gegner zurückzuwerfen.",
        "Dieser magische Angriff kann andere Fertigkeiten auslösen.",
      ],
      color: "blue",
      cost: 2,
    },
    TERROR: {
      name: "SCHRECKEN",
      description: [
        "Bei einem krit. Treffer mit einem Zauber wird das Ziel für 4 Sekunden betäubt.",
      ],
      color: "blue",
      cost: 4,
    },
    SHOCK_RESISTANCE: {
      name: "SHOCK RESISTANCE",
      description: [
        "Increases your <b>Shock Resistance</b> by <b>5%</b> which reduces the amount of <b>Shock</b> damage received.",
      ],
      color: "blue",
      cost: 2,
    },
    QUICK_CHARGE: {
      name: "SCHNELLLADUNG",
      description: [
        "Verringert die Zeit, die Magierstäbe benötigen, um einen Zauber aufzuladen, um 50%.",
      ],
      color: "blue",
      cost: 3,
    },
    THIS_IS_THE_WAY: {
      name: "DIES IST DER WEG",
      description: [
        "Beim Angriff mit einer Magiewaffe wird jeglicher Schaden um 10% erhöht.",
      ],
      color: "blue",
      cost: 2,
    },
    ARSONIST: {
      name: "BRANDSTIFTER",
      description: ["Jeglicher Feuerschaden wird um zusätzlich 10% erhöht."],
      color: "blue",
      cost: 2,
    },
    PYROMANIAC: {
      name: "PYROMANE",
      description: ["Jeglicher Feuerschaden wird um zusätzlich 20% erhöht."],
      color: "blue",
      cost: 3,
    },
    SUN_AURA: {
      name: "SONNENAURA",
      description: [
        "Alle Brutfeinde im Umkreis von 10 Metern erhalten pro Intelligenzpunkt 1 Feuerschaden pro Sekunde.",
      ],
      color: "blue",
      cost: 2,
    },
    FIRE_RESISTANCE: {
      name: "FIRE RESISTANCE",
      description: [
        "Increases your <b>Fire Resistance</b> by <b>5%</b> which reduces the amount of <b>Fire</b> damage received.",
      ],
      color: "blue",
      cost: 2,
    },
    THUNDER: {
      name: "DONNER",
      description: ["Jeglicher Schockschaden wird zusätzlich um 10 % erhöht."],
      color: "blue",
      cost: 2,
    },
    LIGHTNING: {
      name: "BLITZ",
      description: ["Jeglicher Schockschaden wird zusätzlich um 20 % erhöht."],
      color: "blue",
      cost: 3,
    },
    ICEMAN: {
      name: "EISKALT",
      description: ["Jeglicher Eisschaden wird um zusätzlich 10 % erhöht."],
      color: "blue",
      cost: 2,
    },
    SUBZERO: {
      name: "FROSTBISS",
      description: ["Jeglicher Eisschaden wird um zusätzlich 20 % erhöht."],
      color: "blue",
      cost: 3,
    },
    FROST: {
      name: "FROST",
      description: [
        "Nach eingehendem Nahkampfschaden wird der Angreifer für 3 Sekunden verlangsamt.",
      ],
      color: "blue",
      cost: 3,
    },
    ICE_RESISTANCE: {
      name: "ICE RESISTANCE",
      description: [
        "Increases your <b>Ice Resistance</b> by <b>5%</b> which reduces the amount of <b>Ice</b> damage received.",
      ],
      color: "blue",
      cost: 2,
    },
    WIZARD: {
      name: "ZAUBERER",
      description: [
        "Beim Angriff mit einer Magiewaffe erhöht sich deine krit. Trefferchance um 10%.",
      ],
      color: "blue",
      cost: 3,
    },
    DARK_ARTS: {
      name: "DUNKLE KÜNSTE",
      description: ["Jeglicher Miasma-Schaden wird um zusätzlich 10 % erhöht."],
      color: "blue",
      cost: 3,
    },
    ABYSS: {
      name: "ABGRUND",
      description: ["Jeglicher Miasma-Schaden wird um zusätzlich 20 % erhöht."],
      color: "blue",
      cost: 4,
    },
    CHAIN_HIT: {
      name: "KETTENTREFFER",
      description: [
        "Bei einem kritischen Treffer mit einer Magiewaffe trifft der Angriff automatisch eine zweiten Gegner im Umkreis von 15 Metern mit 5 Schockschaden pro Intelligenzpunkt.",
      ],
      color: "blue",
      cost: 3,
    },
    MASS_DESTRUCTION: {
      name: "MASSENVERNICHTUNG",
      description: [
        "Ein kritischer Angriff mit einer magischen Waffe trifft alle Gegner im Umkreis von 20 Metern um das Ziele und verursacht 2 Schockschaden pro Intelligenz.",
      ],
      color: "blue",
      cost: 4,
    },
    NECROMANCER: {
      name: "TOTENBESCHWÖRER",
      description: [
        "Wenndu einen Feind mit einer magischen Waffe tötest, hast du eine Chance von 10%, einen freundlichen Schädelbegleiter zu beschwören.",
      ],
      color: "blue",
      cost: 3,
    },
    HEALER: {
      name: "HEILER",
      description: [
        "Die Regeneration durch Heilzauber wird um 10 % erhöht.",
      ],
      color: "blue",
      cost: 2,
    },
    HEALER_II: {
      name: "HEILER II",
      description: ["Die Regeneration durch Heilzauber wird um zusätzliche 20 % erhöht."],
      color: "blue",
      cost: 2,
    },
    HEALING_REVIVE: {
      name: "NEUE BLÜTE",
      description: [
        "Die Gesundheit wiederbelebter Spieler wird um 25 % statt um 10 % wiederhergestellt.",
      ],
      color: "blue",
      cost: 2,
    },
    SHROUD_FILTER: {
      name: "MIASMA-FILTER",
      description: [
        "Wenn du Magiewaffen-Schaden verursachst, besteht eine Chance von 15 %, einen kleinen Flammenstoß auszulösen, der für dich und deine Verbündeten innerhalb von 20 Metern 30 Sekunden <i>Miasma-Zeit</i> wiederherstellt.",
        SHROUD_TIME_TEXT,
      ],
      color: "blue",
      cost: 3,
    },
    WATERS_OF_LIFE: {
      name: "WASSER DES LEBENS",
      description: [
        "Erhöht die <b>Wasseraura</b> Heilung auf 2 Lebenspunkte pro 2 Punkte Intelligenz.",
      ],
      color: "blue",
      cost: 2,
    },
    SHROUD_RESISTANCE: {
      name: "SHROUD RESISTANCE",
      description: [
        "Increases <b>Shroud Resistance</b> by <b>5%</b> which reduces the amount of <b>Shroud</b> damage received.",
      ],
      color: "blue",
      cost: 2,
    },
    SHROUD_MISTERY: {
      name: "SHROUD MYSTERY",
      description: [
        "When you receive <b>Shroud</b> damage, all players within <b>20</b>-meters receive <b>15%</b> increased <b>Shroud Resistance</b> for <b>30</b> seconds.",
      ],
      color: "blue",
      cost: 6,
    },
    EMERGENCY_BLINK: {
      name: "NOTFALL-TELEPORT",
      description: [
        "Du kannst dich teleportieren, während du betäubt bist. Dies unterbricht den Betäuben-Status.",
      ],
      color: "blue",
      cost: 2,
    },
    BLINK_ATTACK: {
      name: "TELEPORT-ANGRIFF",
      description: [
        "Das Teleportieren in einen Gegner löst eine Explosion aus, die in geringer Reichweite Feuerschaden verursacht.",
        "Schaden und Manakosten skalieren mit dem Intelligent-Attribut.",
      ],
      color: "blue",
      cost: 2,
    },
    ARCANE_DEFLECTION: {
      name: "ARKANE ABLENKUNG",
      description: ["Bei einer erfolgreichen Parade erhältst du 20 Mana."],
      color: "blue",
      cost: 3,
    },
    UNITY: {
      name: "EINHEIT",
      description: [
        "Wenn mit Stäben Schaden gegen Gegner verursacht wird, besteht eine Chance von 24%, dass 4% Mana wiederhergestellt werden.",
      ],
      hasIcon: true,
      color: "blue",
      cost: 3,
    },
    WAND_MASTER: {
      name: "ZAUBERSTABMEISTER",
      description: [
        "Wenn du mit einem Zauberstab angreifst, besteht eine Chance von 30%, dass du ein zusätzliches Projektil erzeugst, dass 50% Schaden verursachst.",
      ],
      color: "blue",
      cost: 3,
    },
    ETERNAL_SPARK: {
      name: "EWIGER FUNKE",
      description: [
        "Zauberstabgeschosse haben eine Chance von 25%, keine Haltbarkeit zu verlieren.",
      ],
      color: "blue",
      cost: 3,
    },
    STING: {
      name: "STACHEL",
      description: ["Wiederholter Schaden mit einem Zauberstab wird um 20 % erhöht."],
      color: "blue",
      cost: 3,
    },
    BATTLE_HEAL: {
      name: "KAMPFHEILUNG",
      description: [
        "Wenn du mit einer Nahkampfwaffe krit. Schaden verursachst, heilst du 5 % deiner max. Gesundheit.",
      ],
      color: "red",
      cost: 3,
    },
    BLOODLETTING: {
      name: "ADERLASS",
      description: [
        "Wenn du mit einem Zauberspruch einen kritischen Treffer landest, besteht eine 50%ige Chance, 2 Gesundheits-, Mana- und/oder Ausdauer Orbs zu spawnen.",
        "Ds Sammeln der Orbs füllt 10% der jeweiligen Ressource wieder auf.",
      ],
      color: "blue",
      cost: 3,
    },
    LIFE_BURST: {
      name: "LEBENSEXPLOSION",
      description: [
        "Wenn du einen Gegner mit einer Magiewaffe tötest, regenerieren alle Spieler im Umkreis von 15 Metern um das Ziel Gesundheit in Höhe des 3-fachen deiner Intelligenz.",
      ],
      color: "blue",
      cost: 4,
    },
    BLOOD_MAGIC: {
      name: "BLUTMAGIE",
      description: [
        "Wenn dein Mana unter 20% fällt, stellst du bis zu 35% deines maximalen Manas wieder her, allerdings auf Kosten von 1 Gesundheit pro Mana. Die Wirkung endet bei 1 Gesundheit.",
        "<b>Abklingezeit.</b><br />Es dauert 2 Minuten, bevor der Effekt wieder ausgelöst werden kann.",
      ],
      color: "blue",
      cost: 4,
    },
    ABSORB: {
      name: "ABSORBIEREN",
      description: [
        "Wenn du Magieschaden erleidest, besteht eine Chance von 10 %, für jeden verlorenen Lebenspunkt 1 Mana zu erzeugen.",
      ],
      color: "red",
      cost: 3,
    },
    SNAP: {
      name: "ÜBERSCHNAPPEN",
      description: ["Stellt 10 % Mana wieder her, wenn ein Gnadenloser Angriff erfolgt."],
      color: "red",
      cost: 4,
    },
    SOUL_LEECH: {
      name: "SEELENERAUB",
      description: [
        "Wenn du einen Gegner mit einer Nahkampfwaffe tötest, erhalten alle Spieler im Umkreis von 15 Metern um das Ziel 20 Mana.",
      ],
      color: "red",
      cost: 4,
    },
    SHINY_PLATES: {
      name: "GLÄNZENDE PLATTEN",
      description: ["Physische Rüstung gewährt 10% mehr physischen Widerstand."],
      color: "red",
      cost: 2,
    },
    HEAVY_PLATES: {
      name: "SCHWERE PLATTEN",
      description: [
        "Die maximale Menge an physischem Schaden, die deine Rüstung abwehren kann, wird um 10% erhöht.",
      ],
      color: "red",
      cost: 2,
    },
    WARDEN: {
      name: "WÄCHTER",
      description: [
        "Wenn sich drei oder mehr Feinde im Umkreis von 20 Metern befinden, erleidest du 15 % weniger Magieschaden.",
      ],
      color: "red",
      cost: 3,
    },
    TOWER: {
      name: "TURM",
      description: [
        "Wenn sich drei oder mehr Feinde im Umkreis von 20 Metern befinden, erleidest du 10 % weniger physischen Schaden.",
      ],
      color: "red",
      cost: 3,
    },
    ARCH_NEMESIS: {
      name: "ERZFEIND",
      description: [
        "Wenn ein Verbündeter die Aufmerksamkeit eines Feindes auf sich zieht, gilt das doppelt für dich.",
      ],
      color: "red",
      cost: 3,
    },
    PURIFICATION: {
      name: "REINIGUNG",
      description: [
        "Wenn du einen vom Miasma verdorbenen Gegner mit einer Nahkampfwaffe besiegst, stellst du +5 Sekunden <i>Miasma-Zeit</i> wieder her.",
        SHROUD_TIME_TEXT,
      ],
      color: "red",
      cost: 3,
    },
    WARRIOR_PATH: {
      name: "DER WEG DES KRIEGERS",
      description: [
        "Beim Angriff mit einer Nahkampfwaffe wird jeglicher Schaden um 10 % erhöht.",
      ],
      color: "red",
      cost: 2,
    },
    THRUST: {
      name: "PFÄHLER",
      description: [
        "Jeglicher Nahkampf-Stichschaden wird um zusätzliche 10 % erhöht.",
      ],
      color: "red",
      cost: 2,
    },
    PIERCE: {
      name: "LANZER",
      description: [
        "Jeglicher Nahkamp-Stichschaden wird um zusätzliche 20 % ehöht.",
      ],
      color: "red",
      cost: 3,
    },
    BRUTE: {
      name: "ROHLING",
      description: [
        "Jeglicher Nahkamp-Wuchtschaden wird um zusätzliche 10 % erhöht.",
      ],
      color: "red",
      cost: 2,
    },
    HAMMER_TIME: {
      name: "HAMMERHART",
      description: [
        "Jeglicher Nahkamp-Wuchtschaden wird um zusätzliche 20 % erhöht.",
      ],
      color: "red",
      cost: 3,
    },
    SLASHER: {
      name: "SCHLITZER",
      description: [
        "Alle Nahkampf-Schnittschäden werden um 10 % erhöht.",
      ],
      color: "red",
      cost: 2,
    },
    BUTCHER: {
      name: "SCHLÄCHTER",
      description: [
        "Alle Nahkampf-Schnittschäden werden um zusätzliche 20 % erhöht.",
      ],
      color: "red",
      cost: 3,
    },
    VETERAN: {
      name: "VETERAN",
      description: [
        "Beim Angriff mit einer Nahkampfwaffe erhöht sich deine Krit. Trefferchance um 10 %.",
      ],
      color: "red",
      cost: 4,
    },
    TITAN_EDGE: {
      name: "TITAN EDGE",
      description: ["Greatswords damage is increased by <b>10%</b>."],
      color: "red",
      cost: 4,
    },
    SWIFT_BLADES: {
      name: "SCHNELLE KLINGEN",
      description: [
        "Ermöglicht es dir, schneller mit einhändigen Schwertern und Äxten anzugreifen.",
      ],
      hasIcon: true,
      color: "red",
      cost: 5,
    },
    FEAST: {
      name: "FESTMAHL",
      description: ["Fleisch erhöht jetzt die Gesundheit um zusätzliche 15%.",],
      color: "red",
      cost: 3,
    },
    HEAVY_HANDED: {
      name: "DICKKÖPFIG",
      description: [
        "Die Betäubungsleiste eines Gegners wird um zusätzliche 20% erhöht, wenn dui mit einer Nahkampfwaffe in dessen Block schlägst.",
      ],
      color: "red",
      cost: 2,
    },
    STEADFAST: {
      name: "UNERSCHÜTTERLICH",
      description: [
        "Wenn du einen Gegner mit einer Nahkampfwaffe besiegst, erhält diese Waffe 1 Haltbarkeit zurück.",
      ],
      color: "red",
      cost: 3,
    },
    UPWARDS_SLASH_ATTACK: {
      name: "UPWARDS SLASH ATTACK",
      description: [
        "When equipped with a Melee weapon, launch a powerful upward strike during the ascent of your jump.",
        "Use this skill to rapidly close the distance on <b>flying</b> enemies.",
        "<b>Cost</b>: 25 Stamina",
      ],
      hasIcon: true,
      color: "red",
      cost: 3,
    },
    BREACH: {
      name: "DURCHBRUCH",
      description: [
        "Ein überwältigter Gegner erleidet 3 Sekunden lang 100% mehr Nahkampfschaden.",
        OVERPOWER,
      ],
      color: "red",
      cost: 3,
    },
    RELENTLESS: {
      name: "UNBARMHERZIG",
      description: [
        "Wenn du mit einer zweihändigen Waffe krit. Schaden verursachst, erhöht sich die Chance, dass der nächste Treffer ein krit. Treffer wird, um weitere 10 %.",
      ],
      color: "red",
      cost: 5,
    },
    BARBARIAN: {
      name: "BARBAR",
      description: [
        "Alle zwei Stufen der Flamme gewähren einen Stärkepunkt.",
      ],
      color: "red",
      cost: 5,
    },
    BLOOD_RAGE: {
      name: "BLUTRAUSCH",
      description: [
        "Wenn ein Gegner innerhlab von 10 Metern mit einer Nahkampfwaffe getötet wird, wird jeglicher mit Nahkampfwaffen verursachte Schaden 10 Sekunden lang um 20 % erhöht.",
      ],
      color: "red",
      cost: 5,
    },
    VIGOROUS_DEFLECTION: {
      name: "KRÄFTIGE UMLENKUNG",
      description: ["Du erhältst 30 Ausdauer, wenn du den Angriff eines Gegners parierst."],
      color: "red",
      cost: 2,
    },
    BLOOD_WARRIOR: {
      name: "BLUTKRIEGER",
      description: [
        "Erzeuge einen Gesundheitsorb, nachdem du einen Gegner mit einem Schleichangriff oder Gnadenloser Angriff besiegt hast.",
        "Wenn du den Orb einsammelst, werden 10% deiner Gesundheit wiederhergestellt.",
      ],
      color: "red",
      cost: 3,
    },
    WET_DOG: {
      name: "WET DOG",
      description: [
        "Weakens the effect of the <b>Wet</b> and <b>Soaked</b> debuffs.",
        "Stamina and Stamina Regeneration are reduced by <b>20%</b> instead of <b>30%</b>.",
        WET,
        SOAKED,
      ],
      color: "red",
      cost: 4,
    },
    SOAKED_DOG: {
      name: "SOAKED DOG",
      description: [
        "Weakens the effect of the <b>Wet</b> and <b>Soaked</b> debuffs.",
        "Stamina and Stamina Regeneration are reduced by <b>10%</b> instead of <b>20%</b>.",
        WET,
        SOAKED,
      ],
      color: "red",
      cost: 2,
    },
    SPLASH_DASH: {
      name: "SPLASH DASH",
      description: [
        "Allows you to perform an evasive dash while swimming or diving.",
        "<b>Cost</b>: 80 Stamina",
      ],
      hasIcon: true,
      color: "red",
      cost: 5,
    },
    FINESSE: {
      name: "FINESSE",
      description: [
        "Einhändige Nahkampfwaffen und Dolche haben eine Chance von 20%, ihre Haltbarkeit nicht zu verlieren.",
      ],
      color: "red",
      cost: 3,
    },
    JUMP_ATTACK_II: {
      name: "SPRUNGANGRIFF II",
      description: [
        "Wenn du mit einer Nahkampfwaffe ausgerüstest bis, verursacht ein Angriff aus einem Doppelsprung zusätzlich 20% Waffenschaden.",
      ],
      color: "green",
      cost: 3,
    },
    BACKSTAB_MASTERY: {
      name: "MEISTERHAFTER HINTERHALT",
      description: ["Jeglicher Schaden von hinten wird um 30% erhöht."],
      color: "green",
      cost: 4,
    },
    RUNNER: {
      name: "LÄUFER",
      description: [
        "Sprint-Geschwindigkeit wird um 10 % erhöht. Ausdauerverbrauch wird um 10 % reduziert.",
      ],
      color: "green",
      cost: 2,
    },
    WANDERLUST: {
      name: "FERNWEH",
      description: [
        "Der Ausdauerverbrauch beim <b>Sprinten auf unbefestigten Straßen</b> wird von <b>90% auf 80%</b> reduziert. Der Ausdauerverbrauch beim <b>Sprinten auf Steinstraßen</b> wird von <b>75% auf 50%</b> reduziert.",
      ],
      color: "green",
      cost: 3,
    },
    GOOD_METABOLISM: {
      name: "GUTER STOFFWECHSEL",
      description: [
        "Gesundheit, Mana und Ausdauer Orbs stellen 30% statt 10% ihrer jeweiligen Ressource wieder her.",
        "Mana- und Heiltränke stellen 20% mehr wieder her.",
      ],
      color: "green",
      cost: 3,
    },
    SWIFTSHOT_SUSTENANCE: {
      name: "ZUSCHUSS",
      description: [
        "30% Chance, einen Ausdauer-Orb zu spawnen, wenn du einen Gegner mit einem Bogen besiegst.",
      ],
      color: "green",
      cost: 2,
    },
    SWEET_TOOTH: {
      name: "SCHLECKERMAUL",
      description: ["Die Ausdauerregeneration durch Süßes wird um 50 % erhöht."],
      color: "green",
      cost: 3,
    },
    ARACHNOID: {
      name: "SPINNENTIER",
      description: ["Der Ausdauerverbrauch beim Klettern wird um 50% reduziert."],
      color: "green",
      cost: 3,
    },
    REBOUND: {
      name: "ATEMTECHNIK",
      description: ["Erhöht Standard-Ausdauerregeneration um 50 %."],
      color: "green",
      cost: 2,
    },
    REBOUND_II: {
      name: "REBOUND",
      description: ["Increase base stamina regeneration by 50%"],
      color: "green",
      cost: 4,
    },
    INNER_FIRES: {
      name: "INNERES FEUER",
      description: [
        "Die max. <i>Miasma-Zeit</i> wird um 2 Minuten erhöht, wodurch du länger erkunden kannst.",
        SHROUD_TIME_TEXT,
      ],
      color: "green",
      cost: 2,
    },
    RELENTLESS_FLAME: {
      name: "UNERBITTERLICHE FLAMME",
      description: [
        "Die max. <i>Miasma-Zeit</i> wird um 5 Minuten erhöht, wodurch du länger erkunden kannst.",
        SHROUD_TIME_TEXT,
      ],
      color: "green",
      cost: 4,
    },
    SNAKE_EATER: {
      name: "SCHLANGENFRESSER",
      description: [
        "Erhöht den <b> -Giftwiderstand</b>, der den erhaltenen Giftschaden um <b>20%</b> reduziert.",
      ],
      color: "green",
      cost: 2,
    },
    MITHRIDATIST: {
      name: "GIFTIMMUNITÄT",
      description: [
        "Deiner Giftresistenz wird um zusätzliche 10% erhöht. Du erhältst eine Chance von 25%, Vergiftungen vollständig zu vermeiden.",
        "You also gain a 25% chance to avoid being poisoned.",
      ],
      color: "green",
      cost: 3,
    },
    DAGGER_MASTER: {
      name: "DOLCHMEISTER",
      description: ["Erhöht den mit Dolchen verursachten Schaden um 15%."],
      color: "green",
      cost: 3,
    },
    SLICE_AND_DICE: {
      name: "STICH UND SCHNITT",
      description: [
        "Erhöht den Schaden deines nächsten Bogenangriffs nach einem kritischen Dolchtreffer um 50%.",
      ],
      color: "green",
      cost: 3,
    },
    VUKAH_LANGUAGE: {
      name: "SPRACHE DER VUKAH",
      description: [
        "Vukah im Umkreis von 50 Metern greifen dich nicht an, bis sie selbst angegriffen werden.",
      ],
      color: "green",
      cost: 3,
    },
    CALM_SPIRIT: {
      name: "RUHIGER GEIST",
      description: [
        "<b>Wilde Tiere</b> im Ukreis von 50 Metern werden befriedet, wenn sie nicht angegriffen werden. Wirkt nicht auf Tiere, die von Miasma verdorben sind.",
      ],
      color: "green",
      cost: 3,
    },
    BEAST_MASTER: {
      name: "BESTIENMEISTER",
      description: [
        "Wenn du von einem Angriff betroffen bist, greifen <b>wilde Tiere</b> um Umkreis von 50 Metern den Gegner an.",
      ],
      color: "green",
      cost: 4,
    },
    VUKAH_CULTURE: {
      name: "KULTUR DER VUKAH",
      description: [
        "Wenn du angegriffen wirst, greifen Vukah im Umkreis von 50 Metern den Gegner an.",
      ],
      color: "green",
      cost: 4,
    },
    ENDURANCE_OF_THE_FLAME: {
      name: "AUSDAUER DER FLAMME",
      description: [
        "Alle zwei Stufen der Flamme gewähren einen Konditionspunkt.",
      ],
      color: "green",
      cost: 5,
    },
    MARKSMAN: {
      name: "SCHÜTZE",
      description: ["Jeglicher Fernkampfschaden wird um 10 % erhöht."],
      color: "green",
      cost: 2,
    },
    SHARPSHOOTER: {
      name: "SCHARFSCHÜTZE",
      description: ["Jeglicher Fernkampfschaden wird um 20 % erhöht."],
      color: "green",
      cost: 2,
    },
    COUNTER_BATTERY: {
      name: "KONTERSALVE",
      description: ["+15 % Schaden gegen Fernkampf-Gegner."],
      color: "green",
      cost: 2,
    },
    EAGLES_BANE: {
      name: "FLUCH DES ADLERS",
      description: ["Der Schaden gegen fliegende Gegner wird um 30% erhöht."],
      color: "green",
      cost: 3,
    },
    SKILL_SHOT: {
      name: "GESCHICKLICHKEITSSCHUSS",
      description: ["Der Schaden am Kopf des Gegners wird um 20% erhöht."],
      color: "green",
      cost: 3,
    },
    RANGER: {
      name: "WALDLÄUFER",
      description: [
        "+2 Kondition<br>+2 Geschick<br>+5 Ausdauer Regeneration<br>+5% Krit. Chance<br>+5% Krit. Schaden",
      ],
      color: "green",
      cost: 4,
      stats: {
        DEX: 2,
        ENDURANCE: 2,
      },
    },
    SILENT_STRIDE: {
      name: "STILLER SCHRITT",
      description: ["Erhöht deine Bewegungsgeschwindigkeit beim Schleichen."],
      color: "green",
      cost: 3,
    },
    KICK: {
      name: "KICK",
      description: [
        "When equipped with a Melee weapon you can perform a Kick by attacking while blocking.",
        "Kick deals little damage but hits the target with massive force to fill up the enemies <i>Stun Bar</i> and pushes them back.",
        "<i>Stun Bar</i> increase scales with Dexterity. Stun time depends on the enemy's size.",
        "<b>Overpower</b><br>Attacking blocking enemies or parrying their attacks fills their <i>Stun Bar</i> until they become <b>overpowered</b>.<br><b>Overpowered</b> enemies are open for Merciless Attacks.",
      ],
      color: "green",
      hasIcon: true,
      cost: 3,
    },
    AIRBORNE: {
      name: "ABGEHOBEN",
      description: ["Gleiter verrbauchen 30 % weniger Ausdauer."],
      color: "green",
      cost: 2,
    },
    SNIPER: {
      name: "HECKENSCHÜTZE",
      description: [
        "Beim Angriff mit einer Fernkampfwaffe erhöht sich deine Krit. Trefferchance um 10 %.",
      ],
      color: "green",
      cost: 2,
    },
    VITALITY_SURGE: {
      name: "VITALITÄTSSCHUB",
      description: [
        "Ein kritischer Treffer mit einer Fernkamopfwaffe stellt 5 Ausdauer wieder her.",
      ],
      color: "green",
      cost: 3,
    },
    BLESSED_ARROWS: {
      name: "GESEGNETE PFEILE",
      description: [
        "Wenn du einen krit. Treffer mit einem Bogen erzielst, regenerierst du 20 Mana.",
      ],
      color: "green",
      cost: 3,
    },
    BOUNTY_BONANZA: {
      name: "KOPFGELD-BONANZA",
      description: [
        "Wenn du einen Brut Gegner mit einem Kopfschuss besiegst, erhält deine Gruppe 5 zusätzliche Erfahrungspunkte.",
      ],
      color: "green",
      cost: 3,
    },
    RICOCHETS: {
      name: "QUERSCHLÄGER",
      description: [
        "Für jedes Ziel, das du mit einem Explosionspfeil triffst, wird der Schaden um 1% erhöht.",
      ],
      color: "green",
      cost: 4,
    },
    GRACEFUL_STRIDE: {
      name: "ANMUTIGER SCHRITT",
      description: [
        "Alle zwei Stufen der Flamme gewähren einen Geschickpunkt.",
      ],
      color: "green",
      cost: 5,
    },
    CHAIN_REACTION: {
      name: "KETTENREAKTION",
      description: [
        "Jeder Gegner, der mit einem Explosionspfeil getroffen wird, hat eine Chance von 20%, eine zweite Explosion auszulösen, die in einem kleinen Radius 50% Schaden verursacht.",
      ],
      color: "green",
      cost: 5,
    },
    ARCANE_CONCENTRATION: {
      name: "ARKANE KONZENTRATION",
      description: [
        "Alle zwei Stufen der Flamme gewähren einen Willenskraftpunkt.",
      ],
      color: "blue",
      cost: 5,
    },
    EXALTED: {
      name: "ERHABEN",
      description: [
        "Alle zwei Stufen der Flamme gewähren einen Intelligenzpunkt.",
      ],
      color: "blue",
      cost: 5,
    },
    THICK_SKIN: {
      name: "DICKES FELL",
      description: [
        "Alle zwei Stufen der Flamme gewähren einen Konstitutionspunkt",
      ],
      color: "red",
      cost: 5,
    },
    LIFE_ESSENCES: {
      name: "LEBENSESSENZEN",
      description: [
        "Deine maximale Gesundheit wird um das Fünffache deines Intelligenzattributs erhöht.",
      ],
      color: "blue",
      hasIcon: true,
      cost: 5,
    },
    POISONED_BLADES: {
      name: "VERGIFTETE KLINGEN",
      description: [
        `Erhöht deine Chance, Feinde zu vergiften, auf 25%, wenn du Dolche mit dem "Vergiftete Klingen" Perk verwendest.`,
      ],
      color: "green",
      cost: 3,
    },
    POISON_MASTERY: {
      name: "MEISTER DES GIFTS",
      description: [
        `Erhöht den mit dem Dolch-Perk "Vergiftete Klingen" verursachten Schaden.`,
      ],
      color: "green",
      cost: 4,
    },
    QUICK_REFLEX_BLOCK: {
      name: "SCHNELLER REFLEX-BLOCK",
      description: [
        "Erhöht kurzzeitig deinen Blockwert beim Blocken mit Dolchen und sorgt dafür, dass eine knapp verfehlte Parade die Ausdauer nur minimal reduziert.",
      ],
      color: "green",
      cost: 4,
    },
    EXPOSE_WEAKNESS: {
      name: "EXPOSE WEAKNESS",
      description: [
        "Critical Strikes with Daggers increase damage dealt to the enemy by <b>25%</b> for <b>3</b> seconds.",
      ],
      color: "green",
      cost: 4,
    },
  },
  nodes: {
    "1": {
      id: "1",
      type: "WELL_RESTED",
      base: true,
      tier: "medium",
      distance: -120,
      angle: 255,
    },
    "2": {
      id: "2",
      type: "SNEAK_ATTACK",
      base: true,
      tier: "large",
      distance: -120,
      angle: 225,
    },
    "3": {
      id: "3",
      type: "BACKSTAB_DAMAGE",
      tier: "medium",
      distance: -190,
      angle: 225,
    },
    "181": {
      id: "181",
      type: "OPPORTUNITY",
      tier: "medium",
      distance: -250,
      angle: 225,
    },
    "4": {
      id: "4",
      type: "LUMBERJACK",
      base: true,
      tier: "medium",
      distance: -120,
      angle: 165,
    },
    "5": {
      id: "5",
      type: "QUALITY_GEAR",
      tier: "medium",
      distance: -120,
      angle: 120,
    },
    "6": { id: "6", type: "MINER", tier: "medium", distance: -190, angle: 120 },
    "7": {
      id: "7",
      type: "MASON",
      base: true,
      tier: "medium",
      distance: -120,
      angle: 75,
    },
    "220": {
      id: "220",
      type: "FISHERMANS_RESOLVE",
      base: true,
      tier: "medium",
      distance: -120,
      angle: 45,
    },
    "8": {
      id: "8",
      type: "MERCILESS_ATTACK",
      base: true,
      tier: "large",
      distance: -120,
      angle: 15,
    },
    "9": {
      id: "9",
      type: "POWER_PARRY",
      tier: "medium",
      distance: -190,
      angle: 15,
    },
    "10": {
      id: "10",
      type: "SAVIOUR",
      base: true,
      tier: "medium",
      distance: -120,
      angle: 315,
    },
    "11": {
      id: "11",
      type: "ATTR_SPIRIT",
      base: true,
      tier: "small",
      angle: 255,
    },
    "12": {
      id: "12",
      type: "COUNTERSTRIKE",
      tier: "medium",
      distance: 70,
      angle: 255,
    },
    "13": {
      id: "13",
      type: "ATTR_INT",
      tier: "small",
      distance: 170,
      angle: 250,
    },
    "14": {
      id: "14",
      type: "ATTR_SPIRIT",
      tier: "small",
      distance: 170,
      angle: 260,
    },
    "15": {
      id: "15",
      type: "BEGONE",
      tier: "large",
      distance: 240,
      angle: 255,
    },
    "17": {
      id: "17",
      type: "ATTR_SPIRIT",
      tier: "small",
      distance: 310,
      angle: 250,
    },
    "16": {
      id: "16",
      type: "ATTR_INT",
      tier: "small",
      distance: 310,
      angle: 260,
    },
    "68": {
      id: "68",
      type: "BLOOD_MAGIC",
      tier: "medium",
      distance: 380,
      angle: 250,
    },
    "64": {
      id: "64",
      type: "BLOODLETTING",
      tier: "medium",
      distance: 380,
      angle: 255,
    },
    "18": {
      id: "18",
      type: "TERROR",
      tier: "medium",
      distance: 380,
      angle: 260,
    },
    "217": {
      id: "217",
      type: "SHOCK_RESISTANCE",
      tier: "medium",
      distance: 450,
      angle: 263,
    },
    "218": {
      id: "218",
      type: "SHOCK_RESISTANCE",
      tier: "medium",
      distance: 520,
      angle: 263,
    },
    "219": {
      id: "219",
      type: "SHOCK_RESISTANCE",
      tier: "medium",
      distance: 590,
      angle: 263,
    },
    "19": {
      id: "19",
      type: "ARCANE_CONCENTRATION",
      tier: "small",
      distance: 450,
      angle: 255,
    },
    "20": {
      id: "20",
      type: "QUICK_CHARGE",
      tier: "medium",
      distance: 120,
      angle: 270,
    },
    "21": { id: "21", type: "ATTR_SPIRIT", base: true, angle: 285 },
    "22": {
      id: "22",
      type: "THIS_IS_THE_WAY",
      tier: "medium",
      distance: 70,
      angle: 285,
    },
    "23": {
      id: "23",
      type: "NECROMANCER",
      tier: "medium",
      distance: 120,
      angle: 300,
    },
    "24": { id: "24", type: "ATTR_SPIRIT", distance: 140, angle: 285 },
    "25": {
      id: "25",
      type: "ARSONIST",
      tier: "medium",
      distance: 210,
      angle: 277,
    },
    "26": {
      id: "26",
      type: "THUNDER",
      tier: "medium",
      distance: 210,
      angle: 285,
    },
    "27": {
      id: "27",
      type: "ICEMAN",
      tier: "medium",
      distance: 210,
      angle: 294,
    },
    "211": {
      id: "211",
      type: "ICE_RESISTANCE",
      tier: "medium",
      distance: 250,
      angle: 300,
    },
    "28": {
      id: "28",
      type: "PYROMANIAC",
      tier: "medium",
      distance: 280,
      angle: 277,
    },
    "29": {
      id: "29",
      type: "RADIANT_AURA",
      tier: "large",
      distance: 350,
      angle: 273,
    },
    "30": {
      id: "30",
      type: "SUN_AURA",
      tier: "medium",
      distance: 420,
      angle: 273,
    },
    "214": {
      id: "214",
      type: "FIRE_RESISTANCE",
      tier: "medium",
      distance: 490,
      angle: 271,
    },
    "215": {
      id: "215",
      type: "FIRE_RESISTANCE",
      tier: "medium",
      distance: 560,
      angle: 271,
    },
    "216": {
      id: "216",
      type: "FIRE_RESISTANCE",
      tier: "medium",
      distance: 630,
      angle: 271,
    },
    "31": { id: "31", type: "ATTR_SPIRIT", distance: 490, angle: 276 },
    "32": {
      id: "32",
      type: "LIGHTNING",
      tier: "medium",
      distance: 280,
      angle: 285,
    },
    "33": {
      id: "33",
      type: "SUBZERO",
      tier: "medium",
      distance: 280,
      angle: 294,
    },
    "212": {
      id: "212",
      type: "ICE_RESISTANCE",
      tier: "medium",
      distance: 320,
      angle: 300,
    },
    "34": {
      id: "34",
      type: "FROST",
      tier: "medium",
      distance: 350,
      angle: 294,
    },
    "213": {
      id: "213",
      type: "ICE_RESISTANCE",
      tier: "medium",
      distance: 390,
      angle: 300,
    },
    "35": { id: "35", type: "ATTR_INT", distance: 350, angle: 285 },
    "36": {
      id: "36",
      type: "WIZARD",
      tier: "medium",
      distance: 420,
      angle: 285,
    },
    "37": {
      id: "37",
      type: "DARK_ARTS",
      tier: "medium",
      distance: 490,
      angle: 282,
    },
    "38": {
      id: "38",
      type: "CHAIN_HIT",
      tier: "medium",
      distance: 490,
      angle: 288,
    },
    "39": {
      id: "39",
      type: "ABYSS",
      tier: "medium",
      distance: 560,
      angle: 282,
    },
    "40": {
      id: "40",
      type: "MASS_DESTRUCTION",
      tier: "medium",
      distance: 560,
      angle: 288,
    },
    "41": { id: "41", type: "ATTR_INT", distance: 630, angle: 285 },
    "42": { id: "42", type: "ATTR_INT", base: true, angle: 315 },
    "43": {
      id: "43",
      type: "HEALER",
      tier: "medium",
      distance: 70,
      angle: 315,
    },
    "44": {
      id: "44",
      type: "HEALER_II",
      tier: "medium",
      distance: 140,
      angle: 315,
    },
    "45": { id: "45", type: "ATTR_INT", distance: 210, angle: 315 },
    "46": {
      id: "46",
      type: "WATER_AURA",
      tier: "large",
      distance: 280,
      angle: 320,
    },
    "47": {
      id: "47",
      type: "HEALING_REVIVE",
      tier: "medium",
      distance: 280,
      angle: 310,
    },
    "48": {
      id: "48",
      type: "SHROUD_FILTER",
      tier: "medium",
      distance: 330,
      angle: 325,
    },
    "49": {
      id: "49",
      type: "WATERS_OF_LIFE",
      tier: "medium",
      distance: 330,
      angle: 315,
    },
    "205": {
      id: "205",
      type: "SHROUD_RESISTANCE",
      tier: "medium",
      distance: 390,
      angle: 330,
    },
    "206": {
      id: "206",
      type: "SHROUD_RESISTANCE",
      tier: "medium",
      distance: 460,
      angle: 330,
    },
    "207": {
      id: "207",
      type: "SHROUD_RESISTANCE",
      tier: "medium",
      distance: 530,
      angle: 330,
    },
    "208": {
      id: "208",
      type: "SHROUD_MISTERY",
      tier: "medium",
      distance: 600,
      angle: 330,
    },
    "50": { id: "50", type: "ATTR_SPIRIT", distance: 340, angle: 306 },
    "51": { id: "51", type: "ATTR_INT", distance: 410, angle: 312 },
    "52": { id: "52", type: "ATTR_SPIRIT", distance: 410, angle: 318 },
    "53": {
      id: "53",
      type: "MARTYR",
      tier: "large",
      distance: 480,
      angle: 315,
    },
    "209": {
      id: "209",
      type: "DIVINE_SURGE",
      tier: "medium",
      distance: 530,
      angle: 320,
    },
    "210": {
      id: "210",
      type: "RIGHTEOUS_FIRE",
      tier: "medium",
      distance: 560,
      angle: 315,
    },
    "55": { id: "55", type: "BLINK", tier: "large", distance: 120, angle: 330 },
    "56": {
      id: "56",
      type: "EMERGENCY_BLINK",
      tier: "medium",
      distance: 180,
      angle: 327,
    },
    "57": {
      id: "57",
      type: "BLINK_ATTACK",
      tier: "medium",
      distance: 180,
      angle: 333,
    },
    "62": { id: "62", type: "ATTR_SPIRIT", distance: 240, angle: 330 },
    "58": { id: "58", type: "ATTR_INT", base: true, angle: 345 },
    "59": {
      id: "59",
      type: "ARCANE_DEFLECTION",
      tier: "medium",
      distance: 70,
      angle: 345,
    },
    "60": {
      id: "60",
      type: "EVASION_ATTACK",
      tier: "large",
      distance: 120,
      angle: 360,
    },
    "61": {
      id: "61",
      type: "BATTLE_HEAL",
      tier: "medium",
      distance: 190,
      angle: 360,
    },
    "69": { id: "69", type: "ATTR_INT", distance: 140, angle: 345 },
    "70": { id: "70", type: "UNITY", tier: "large", distance: 210, angle: 345 },
    "72": {
      id: "72",
      type: "STING",
      tier: "medium",
      distance: 270,
      angle: 350,
    },
    "66": {
      id: "66",
      type: "LIFE_BURST",
      tier: "medium",
      distance: 330,
      angle: 354,
    },
    "71": {
      id: "71",
      type: "WAND_MASTER",
      tier: "medium",
      distance: 270,
      angle: 340,
    },
    "180": {
      id: "180",
      type: "ETERNAL_SPARK",
      tier: "medium",
      distance: 330,
      angle: 336,
    },
    "73": { id: "73", type: "ATTR_SPIRIT", distance: 350, angle: 348 },
    "74": { id: "74", type: "ATTR_INT", distance: 350, angle: 342 },
    "188": {
      id: "188",
      type: "LIFE_ESSENCES",
      tier: "large",
      distance: 420,
      angle: 345,
    },
    "54": { id: "54", type: "EXALTED", distance: 490, angle: 345 },
    "75": { id: "75", type: "ATTR_CONS", base: true, angle: 15 },
    "76": {
      id: "76",
      type: "SHINY_PLATES",
      tier: "medium",
      distance: 70,
      angle: 15,
    },
    "77": {
      id: "77",
      type: "HEAVY_PLATES",
      tier: "medium",
      distance: 140,
      angle: 15,
    },
    "78": {
      id: "78",
      type: "ATTR_CONS",
      tier: "small",
      distance: 210,
      angle: 15,
    },
    "79": { id: "79", type: "TOWER", tier: "medium", distance: 280, angle: 20 },
    "80": {
      id: "80",
      type: "WARDEN",
      tier: "medium",
      distance: 280,
      angle: 10,
    },
    "63": {
      id: "63",
      type: "ABSORB",
      tier: "medium",
      distance: 350,
      angle: 5,
    },
    "65": { id: "65", type: "SNAP", tier: "medium", distance: 420, angle: 5 },
    "67": {
      id: "67",
      type: "SOUL_LEECH",
      tier: "medium",
      distance: 490,
      angle: 5,
    },
    "81": { id: "81", type: "ATTR_STR", distance: 350, angle: 25 },
    "82": { id: "82", type: "ATTR_STR", distance: 350, angle: 18 },
    "83": { id: "83", type: "ATTR_CONS", distance: 350, angle: 12 },
    "84": {
      id: "84",
      type: "NEMESIS",
      tier: "large",
      distance: 420,
      angle: 25,
    },
    "85": {
      id: "85",
      type: "ARCH_NEMESIS",
      tier: "medium",
      distance: 490,
      angle: 25,
    },
    "86": {
      id: "86",
      type: "EARTH_AURA",
      tier: "large",
      distance: 480,
      angle: 15,
    },
    "87": { id: "87", type: "THICK_SKIN", distance: 550, angle: 15 },
    "88": { id: "88", type: "ATTR_CONS", base: true, angle: 45 },
    "89": {
      id: "89",
      type: "WARRIOR_PATH",
      tier: "medium",
      distance: 70,
      angle: 45,
    },
    "90": {
      id: "90",
      type: "PURIFICATION",
      tier: "medium",
      distance: 120,
      angle: 30,
    },
    "91": { id: "91", type: "ATTR_STR", distance: 140, angle: 45 },
    "92": {
      id: "92",
      type: "SLASHER",
      tier: "medium",
      distance: 210,
      angle: 55,
    },
    "93": { id: "93", type: "BRUTE", tier: "medium", distance: 210, angle: 45 },
    "94": {
      id: "94",
      type: "THRUST",
      tier: "medium",
      distance: 210,
      angle: 35,
    },
    "95": {
      id: "95",
      type: "BUTCHER",
      tier: "medium",
      distance: 280,
      angle: 55,
    },
    "96": {
      id: "96",
      type: "HAMMER_TIME",
      tier: "medium",
      distance: 280,
      angle: 45,
    },
    "97": {
      id: "97",
      type: "PIERCE",
      tier: "medium",
      distance: 280,
      angle: 35,
    },
    "98": {
      id: "98",
      type: "VETERAN",
      tier: "medium",
      distance: 350,
      angle: 50,
    },
    "204": {
      id: "204",
      type: "TITAN_EDGE",
      tier: "medium",
      distance: 350,
      angle: 40,
    },
    "99": { id: "99", type: "ATTR_CONS", distance: 420, angle: 50 },
    "100": { id: "100", type: "ATTR_STR", distance: 420, angle: 40 },
    "101": {
      id: "101",
      type: "SWIFT_BLADES",
      tier: "large",
      distance: 490,
      angle: 45,
    },
    "102": { id: "102", type: "ATTR_CONS", distance: 560, angle: 45 },
    "103": { id: "103", type: "ATTR_STR", base: true, angle: 75 },
    "104": {
      id: "104",
      type: "HEAVY_HANDED",
      tier: "medium",
      distance: 70,
      angle: 75,
    },
    "183": {
      id: "183",
      type: "STEADFAST",
      tier: "medium",
      distance: 120,
      angle: 90,
    },
    "202": {
      id: "202",
      type: "UPWARDS_SLASH_ATTACK",
      tier: "large",
      distance: 190,
      angle: 90,
    },
    "105": { id: "105", type: "ATTR_STR", distance: 140, angle: 75 },
    "106": {
      id: "106",
      type: "FEAST",
      tier: "medium",
      distance: 120,
      angle: 60,
    },
    "107": { id: "107", type: "ATTR_CONS", distance: 210, angle: 75 },
    "108": {
      id: "108",
      type: "RELENTLESS",
      tier: "medium",
      distance: 280,
      angle: 80,
    },
    "109": {
      id: "109",
      type: "BREACH",
      tier: "medium",
      distance: 280,
      angle: 70,
    },
    "110": {
      id: "110",
      type: "SHOCKWAVE",
      tier: "large",
      distance: 350,
      angle: 60,
    },
    "111": { id: "111", type: "ATTR_CONS", distance: 380, angle: 75 },
    "112": {
      id: "112",
      type: "HEAVY_SPECIALIZATION",
      tier: "large",
      distance: 450,
      angle: 75,
    },
    "113": { id: "113", type: "BARBARIAN", distance: 520, angle: 75 },
    "114": {
      id: "114",
      type: "BLOOD_RAGE",
      tier: "medium",
      distance: 590,
      angle: 75,
    },
    "115": { id: "115", type: "ATTR_STR", base: true, angle: 105 },
    "116": {
      id: "116",
      type: "CRASH_DOWN_ATTACK",
      tier: "large",
      distance: 70,
      angle: 105,
    },
    "117": {
      id: "117",
      type: "DOUBLE_JUMP",
      tier: "large",
      distance: 120,
      angle: 120,
    },
    "118": {
      id: "118",
      type: "JUMP_ATTACK_II",
      tier: "medium",
      distance: 190,
      angle: 120,
    },
    "119": { id: "119", type: "ATTR_STR", distance: 190, angle: 105 },
    "120": {
      id: "120",
      type: "BLOOD_WARRIOR",
      tier: "medium",
      distance: 340,
      angle: 105,
    },
    "199": {
      id: "199",
      type: "WET_DOG",
      tier: "medium",
      distance: 470,
      angle: 105,
    },
    "200": {
      id: "200",
      type: "SOAKED_DOG",
      tier: "medium",
      distance: 490,
      angle: 100,
    },
    "201": {
      id: "201",
      type: "SPLASH_DASH",
      tier: "large",
      distance: 550,
      angle: 105,
    },
    "182": {
      id: "182",
      type: "FINESSE",
      tier: "medium",
      distance: 260,
      angle: 110,
    },
    "178": {
      id: "178",
      type: "BACKSTAB_MASTERY",
      tier: "medium",
      distance: 310,
      angle: 120,
    },
    "121": {
      id: "121",
      type: "VIGOROUS_DEFLECTION",
      tier: "medium",
      distance: 260,
      angle: 100,
    },
    "122": { id: "122", type: "ATTR_CONS", distance: 620, angle: 105 },
    "123": { id: "123", type: "ATTR_CONS", distance: 400, angle: 110 },
    "124": { id: "124", type: "ATTR_STR", distance: 400, angle: 100 },
    "125": { id: "125", type: "BASH", tier: "large", distance: 310, angle: 90 },
    "126": { id: "126", type: "ATTR_STR", distance: 380, angle: 90 },
    "203": {
      id: "203",
      type: "WHIRLWIND_CRESCENDO",
      tier: "large",
      distance: 480,
      angle: 90,
    },
    "127": { id: "127", type: "ATTR_ENDURANCE", base: true, angle: 135 },
    "128": {
      id: "128",
      type: "RUNNER",
      tier: "medium",
      distance: 70,
      angle: 135,
    },
    "129": {
      id: "129",
      type: "INNER_FIRES",
      tier: "medium",
      distance: 120,
      angle: 150,
    },
    "179": {
      id: "179",
      type: "RELENTLESS_FLAME",
      tier: "medium",
      distance: 190,
      angle: 150,
    },
    "130": { id: "130", type: "ATTR_ENDURANCE", distance: 140, angle: 135 },
    "131": {
      id: "131",
      type: "WANDERLUST",
      tier: "medium",
      distance: 210,
      angle: 135,
    },
    "132": {
      id: "132",
      type: "GOOD_METABOLISM",
      tier: "medium",
      distance: 280,
      angle: 140,
    },
    "133": {
      id: "133",
      type: "SWIFTSHOT_SUSTENANCE",
      tier: "medium",
      distance: 280,
      angle: 130,
    },
    "134": { id: "134", type: "REBOUND", distance: 300, angle: 135 },
    "197": { id: "197", type: "REBOUND", distance: 340, angle: 135 },
    "198": { id: "198", type: "REBOUND_II", distance: 380, angle: 135 },
    "135": {
      id: "135",
      type: "SWEET_TOOTH",
      tier: "medium",
      distance: 370,
      angle: 140,
    },
    "136": {
      id: "136",
      type: "ARACHNOID",
      tier: "medium",
      distance: 370,
      angle: 130,
    },
    "137": { id: "137", type: "ATTR_DEX", distance: 440, angle: 135 },
    "138": {
      id: "138",
      type: "DESSERT_STOMACH",
      tier: "large",
      distance: 510,
      angle: 135,
    },
    "196": {
      id: "196",
      type: "LAST_MEAL",
      tier: "medium",
      distance: 510,
      angle: 130,
    },
    "139": { id: "139", type: "ATTR_ENDURANCE", distance: 580, angle: 135 },
    "140": { id: "140", type: "ATTR_ENDURANCE", base: true, angle: 165 },
    "141": {
      id: "141",
      type: "SNAKE_EATER",
      tier: "medium",
      distance: 70,
      angle: 165,
    },
    "142": {
      id: "142",
      type: "EAGLE_EYE",
      tier: "large",
      distance: 120,
      angle: 180,
    },
    "143": {
      id: "143",
      type: "MITHRIDATIST",
      tier: "medium",
      distance: 140,
      angle: 165,
    },
    "144": { id: "144", type: "ATTR_ENDURANCE", distance: 210, angle: 165 },
    "184": {
      id: "184",
      type: "DAGGER_MASTER",
      tier: "medium",
      distance: 280,
      angle: 160,
    },
    "189": {
      id: "189",
      type: "POISONED_BLADES",
      tier: "medium",
      distance: 350,
      angle: 153,
    },
    "190": {
      id: "190",
      type: "POISON_MASTERY",
      tier: "medium",
      distance: 420,
      angle: 155,
    },
    "185": {
      id: "185",
      type: "SLICE_AND_DICE",
      tier: "medium",
      distance: 280,
      angle: 170,
    },
    "191": {
      id: "191",
      type: "QUICK_REFLEX_BLOCK",
      tier: "medium",
      distance: 350,
      angle: 177,
    },
    "195": {
      id: "195",
      type: "EXPOSE_WEAKNESS",
      tier: "medium",
      distance: 420,
      angle: 175,
    },
    "145": {
      id: "145",
      type: "VUKAH_LANGUAGE",
      tier: "medium",
      distance: 420,
      angle: 170,
    },
    "146": {
      id: "146",
      type: "CALM_SPIRIT",
      tier: "medium",
      distance: 420,
      angle: 160,
    },
    "147": { id: "147", type: "ATTR_DEX", distance: 350, angle: 168 },
    "148": { id: "148", type: "ATTR_ENDURANCE", distance: 350, angle: 162 },
    "149": {
      id: "149",
      type: "VUKAH_CULTURE",
      tier: "medium",
      distance: 510,
      angle: 170,
    },
    "150": {
      id: "150",
      type: "BEAST_MASTER",
      tier: "medium",
      distance: 510,
      angle: 160,
    },
    "151": { id: "151", type: "ATTR_DEX", distance: 465, angle: 165 },
    "152": {
      id: "152",
      type: "ENDURANCE_OF_THE_FLAME",
      distance: 580,
      angle: 165,
    },
    "153": { id: "153", type: "ATTR_DEX", base: true, angle: 195 },
    "154": {
      id: "154",
      type: "MARKSMAN",
      tier: "medium",
      distance: 70,
      angle: 195,
    },
    "155": {
      id: "155",
      type: "SILENT_STRIDE",
      tier: "medium",
      distance: 120,
      angle: 210,
    },
    "194": {
      id: "194",
      type: "KICK",
      tier: "large",
      distance: 200,
      angle: 210,
    },
    "156": {
      id: "156",
      type: "SHARPSHOOTER",
      tier: "medium",
      distance: 200,
      angle: 200,
    },
    "157": {
      id: "157",
      type: "COUNTER_BATTERY",
      tier: "medium",
      distance: 200,
      angle: 190,
    },
    "158": {
      id: "158",
      type: "EAGLES_BANE",
      tier: "medium",
      distance: 320,
      angle: 200,
    },
    "159": {
      id: "159",
      type: "SKILL_SHOT",
      tier: "medium",
      distance: 320,
      angle: 190,
    },
    "160": {
      id: "160",
      type: "BEE_STING",
      tier: "large",
      distance: 400,
      angle: 205,
    },
    "161": {
      id: "161",
      type: "RANGER",
      tier: "medium",
      distance: 420,
      angle: 195,
    },
    "162": {
      id: "162",
      type: "MULTI_SHOT",
      tier: "large",
      distance: 400,
      angle: 185,
    },
    "186": {
      id: "186",
      type: "MULTI_SHOT_SPREAD",
      tier: "medium",
      distance: 470,
      angle: 183,
    },
    "187": {
      id: "187",
      type: "MULTI_SHOT_TRIGGER",
      tier: "medium",
      distance: 530,
      angle: 185,
    },
    "163": { id: "163", type: "ATTR_DEX", base: true, angle: 225 },
    "164": {
      id: "164",
      type: "AIRBORNE",
      tier: "medium",
      distance: 70,
      angle: 225,
    },
    "165": {
      id: "165",
      type: "UPDRAFT",
      tier: "large",
      distance: 120,
      angle: 240,
    },
    "166": { id: "166", type: "ATTR_ENDURANCE", distance: 140, angle: 225 },
    "167": {
      id: "167",
      type: "SNIPER",
      tier: "medium",
      distance: 210,
      angle: 225,
    },
    "168": {
      id: "168",
      type: "VITALITY_SURGE",
      tier: "medium",
      distance: 280,
      angle: 230,
    },
    "169": {
      id: "169",
      type: "BLESSED_ARROWS",
      tier: "medium",
      distance: 280,
      angle: 220,
    },
    "170": { id: "170", type: "ATTR_DEX", distance: 350, angle: 235 },
    "171": {
      id: "171",
      type: "SHELL_SHOCK",
      tier: "large",
      distance: 420,
      angle: 235,
    },
    "172": {
      id: "172",
      type: "BOUNTY_BONANZA",
      tier: "medium",
      distance: 350,
      angle: 225,
    },
    "173": { id: "173", type: "ATTR_DEX", distance: 350, angle: 215 },
    "174": {
      id: "174",
      type: "RICOCHETS",
      tier: "medium",
      distance: 420,
      angle: 225,
    },
    "175": { id: "175", type: "GRACEFUL_STRIDE", distance: 490, angle: 225 },
    "176": { id: "176", type: "ATTR_ENDURANCE", distance: 490, angle: 220 },
    "177": {
      id: "177",
      type: "CHAIN_REACTION",
      tier: "medium",
      distance: 560,
      angle: 225,
    },
    "192": {
      id: "192",
      type: "GIANT_SLAYER_HOOK",
      base: true,
      tier: "large",
      distance: -100,
      angle: 285,
    },
    "193": {
      id: "193",
      type: "GROUNDING_HOOK",
      tier: "large",
      distance: -180,
      angle: 295,
    },
  },
  edges: {
    "1": [],
    "2": ["3"],
    "3": ["2", "181"],
    "181": ["3", "9"],
    "4": ["5", "6"],
    "5": ["4", "7"],
    "6": ["4", "7"],
    "7": ["5", "6"],
    "8": ["9"],
    "9": ["8", "181"],
    "10": [],
    "11": ["12"],
    "12": ["11", "13", "14", "20", "165"],
    "13": ["12", "15"],
    "14": ["12", "15"],
    "15": ["13", "14", "16", "17"],
    "16": ["15", "18", "64"],
    "17": ["15", "68", "64"],
    "18": ["16", "19", "217"],
    "19": ["18", "68"],
    "20": ["12", "22"],
    "21": ["22"],
    "22": ["20", "24", "23", "21"],
    "23": ["22", "43"],
    "24": ["22", "25", "26", "27"],
    "25": ["24", "28"],
    "26": ["24", "32"],
    "27": ["24", "33", "211"],
    "28": ["25", "29", "35"],
    "29": ["28", "30"],
    "30": ["29", "31", "214"],
    "31": ["30"],
    "32": ["26", "35"],
    "33": ["27", "35", "34", "212"],
    "34": ["33", "213"],
    "35": ["28", "32", "33", "36"],
    "36": ["35", "37", "38"],
    "37": ["36", "39"],
    "38": ["36", "40"],
    "39": ["37"],
    "40": ["38", "41"],
    "41": ["40"],
    "42": ["43"],
    "43": ["42", "23", "44", "55"],
    "44": ["43", "45"],
    "45": ["44", "47", "46"],
    "46": ["45", "48", "49", "52"],
    "47": ["45", "50", "51"],
    "48": ["46", "205"],
    "49": ["46"],
    "50": ["47"],
    "51": ["47", "53"],
    "52": ["46", "53"],
    "53": ["51", "52", "209", "210"],
    "54": ["188"],
    "55": ["43", "56", "57", "59"],
    "56": ["55", "62"],
    "57": ["55", "62"],
    "58": ["59"],
    "59": ["58", "55", "69", "60"],
    "60": ["59", "76", "61"],
    "61": ["60"],
    "62": ["56", "57"],
    "63": ["65"],
    "64": ["16", "17"],
    "65": ["63", "67"],
    "66": ["72"],
    "67": ["65"],
    "68": ["17", "19"],
    "69": ["59", "70"],
    "70": ["69", "72", "73", "71", "74"],
    "71": ["70", "180"],
    "72": ["70", "66"],
    "73": ["70", "188"],
    "74": ["70", "188"],
    "75": ["76"],
    "76": ["75", "60", "77", "90"],
    "77": ["76", "78"],
    "78": ["77", "80", "79"],
    "79": ["78", "81", "82"],
    "80": ["78", "83", "63"],
    "81": ["79", "84"],
    "82": ["79", "86"],
    "83": ["80", "86"],
    "84": ["81", "85"],
    "85": ["84"],
    "86": ["82", "83", "87"],
    "87": ["86"],
    "88": ["89"],
    "89": ["88", "90", "91", "106"],
    "90": ["89", "76"],
    "91": ["89", "92", "93", "94"],
    "92": ["91", "95"],
    "93": ["91", "96"],
    "94": ["91", "97"],
    "95": ["92", "98"],
    "96": ["93", "98", "204"],
    "97": ["94", "204"],
    "98": ["95", "96", "99", "101"],
    "99": ["98"],
    "100": ["204"],
    "101": ["98", "102", "204"],
    "102": ["101"],
    "103": ["104"],
    "104": ["103", "106", "105", "183"],
    "183": ["104", "116", "202"],
    "105": ["104", "107"],
    "106": ["104", "89"],
    "107": ["105", "108", "109"],
    "108": ["107", "111", "125"],
    "109": ["107", "111", "110"],
    "110": ["109"],
    "111": ["108", "109", "112"],
    "112": ["111", "113"],
    "113": ["112", "114"],
    "114": ["113"],
    "115": ["116"],
    "116": ["115", "117", "119", "183"],
    "117": ["116", "118", "128"],
    "118": ["117"],
    "119": ["116", "182", "121"],
    "120": ["182", "121", "123", "124"],
    "182": ["119", "178", "120"],
    "121": ["119", "125", "120"],
    "122": ["201"],
    "123": ["199", "120"],
    "124": ["199", "120"],
    "125": ["121", "108", "126"],
    "126": ["125", "203"],
    "127": ["128"],
    "128": ["127", "117", "130", "129"],
    "129": ["128", "141", "179"],
    "130": ["128", "131"],
    "131": ["130", "132", "133"],
    "132": ["131", "135", "134"],
    "133": ["131", "136", "178", "134"],
    "134": ["132", "197", "133"],
    "135": ["132", "137"],
    "136": ["133", "137"],
    "137": ["135", "136", "138"],
    "138": ["137", "139", "196"],
    "139": ["138"],
    "140": ["141"],
    "141": ["140", "129", "143", "142"],
    "142": ["141", "154"],
    "143": ["141", "144"],
    "144": ["143", "185", "184"],
    "184": ["144", "148", "189"],
    "185": ["144", "147", "191"],
    "145": ["147", "151", "149"],
    "146": ["148", "151", "150"],
    "147": ["145", "185"],
    "148": ["184", "146"],
    "149": ["145", "152"],
    "150": ["146", "152"],
    "151": ["145", "146"],
    "152": ["149", "150"],
    "153": ["154"],
    "154": ["153", "142", "155", "156", "157"],
    "155": ["154", "164", "194"],
    "156": ["154", "159"],
    "157": ["154", "158"],
    "158": ["157", "160", "161"],
    "159": ["156", "161", "162"],
    "160": ["158"],
    "161": ["158", "159"],
    "162": ["159", "186"],
    "186": ["162", "187"],
    "187": ["186"],
    "163": ["164"],
    "164": ["163", "165", "166", "155"],
    "165": ["164", "12"],
    "166": ["164", "167"],
    "167": ["166", "168", "169"],
    "168": ["167", "170", "172"],
    "169": ["167", "172", "173"],
    "170": ["168", "171"],
    "171": ["170"],
    "172": ["168", "169", "174"],
    "173": ["169"],
    "174": ["175", "176", "172"],
    "175": ["174", "177"],
    "176": ["174"],
    "177": ["175"],
    "178": ["182", "133"],
    "179": ["129"],
    "180": ["71", "205"],
    "188": ["54", "73", "74"],
    "189": ["184", "190"],
    "190": ["189"],
    "191": ["185", "195"],
    "192": ["193"],
    "193": ["192"],
    "194": ["155"],
    "195": ["191"],
    "196": ["138"],
    "197": ["134", "198"],
    "198": ["197"],
    "199": ["123", "124", "200", "201"],
    "200": ["199"],
    "201": ["199", "122"],
    "202": ["183"],
    "203": ["126"],
    "204": ["96", "97", "100", "101"],
    "205": ["48", "206", "180"],
    "206": ["205", "207"],
    "207": ["206", "208"],
    "208": ["207"],
    "209": ["53"],
    "210": ["53"],
    "211": ["27"],
    "212": ["33"],
    "213": ["34"],
    "214": ["30", "215"],
    "215": ["214", "216"],
    "216": ["215"],
    "217": ["18", "218"],
    "218": ["217", "219"],
    "219": ["218"],
    "220": [],
  },
};

export default SkillNodes;
